services:
  app:
    build: .
    container_name: reflex_app
    volumes:
      - .:/app
      - /app/e2e # creates an empty directory so reflex does not hot reload after changes in the e2e folder
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_POOL_SIZE: 10
      SQLALCHEMY_MAX_OVERFLOW: 20
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: reflex_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reflex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reflex_db"]
      interval: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
